name: starlabstheme
version: '0.4.3'
architectures: [all]
summary: Star Labs Theme.
description: |
  The Star Labs theme, originally forked from Yaru, is a theme built to suit the Phase II laptops from Star Labs.

  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select the "StarLabs" session from the login screen.

  More information is available at
  https://starlabs.systems
icon: snap/gui/star.png
grade: stable
confinement: strict

parts:
  theme:
    source: .
    plugin: meson
    build-packages: ["sassc", "libglib2.0-dev"]
    meson-parameters: ["--prefix=/"]
    override-build: |
      # First run normal build stage (the build stage of the meson plugin)
      snapcraftctl build
      # Link session file
      ln -s snap/session $SNAPCRAFT_PART_INSTALL/session
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0


