name: starlabstheme
version: '0.1'
architectures: [all]
summary: Star Labs Gnome theme.
description: |
  Star Labs theme contains a GNOME shell theme and GTK theme.

  More information is available at
  https://starlabs.systems
icon: snap/assets/star.png
grade: testing
confinement: strict

parts:
  theme:
    source: .
    plugin: meson
    build-packages: ["sassc", "libglib2.0-dev"]
    meson-parameters: ["--prefix=/"]
    override-build: |
      # Rename the theme name to previous name for backward compatibility
      # sed -i 's/Yaru/Communitheme/' meson.build
      # First run normal build stage (the build stage of the meson plugin)
      snapcraftctl build
      # Link session file
      ln -s snap/session $SNAPCRAFT_PART_INSTALL/session
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0

