name: starlabstheme
version: '0.4'
architectures: [all]
summary: Star Labs Theme.
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on Ubuntu 18.04 LTS.

  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select the "Ubuntu with communitheme snap" session from the login screen.

  More information is available at
  https://starlabs.systems
icon: snap/gui/star.png
grade: devel
confinement: strict

parts:
  theme:
    source: .
    plugin: meson
    build-packages: ["sassc", "libglib2.0-dev"]
    meson-parameters: ["--prefix=/"]
    override-build: |
      # First run normal build stage (the build stage of the meson plugin)
      snapcraftctl build
      # Link session file
      ln -s snap/session $SNAPCRAFT_PART_INSTALL/session
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0
      # don't support dark variant until it's ready
      #rm -r $SNAPCRAFT_PART_INSTALL/share/themes/*-dark
